### ISSUE TITLE
Add support for font-size too

### ISSUE THREAD

**Issue by rfgamaral** [bentx/vscode-custom-theme#7]
I love the concept behind this extension until VS Code implements proper capabilities for themes. But I miss being able to personalize one specific `font-size:`

**workbench.main.css:14:**

```css
.monaco-workbench>.part>.content {
    font-size: 13px;
}
```

Would you be interested in adding support for this?
